version: "3.7"

services:
    janus_streamer:
        build:
          context: .
        ports:
          - "8088:8088"
          - "8089:8089"
        env_file: ./.env
#        network_mode: "host"
        volumes:
         - ./conf:/opt/janus/etc/janus
         - ./keys:/keys
        ulimits:
          nproc: 65535
          nofile:
            soft: 100000
            hard: 100000
